### PR TITLE
Fix issues related to static/gulp generator files

### LINKED ISSUE #145: Default index.html for static generator is missing/inaccurate
Expected behavior:

- `one-base:static` with `useNunjucks: false` creates a default `index.html` in the root of the project.
- `one-base:static` with `useNunjucks: true` creates a default `index.html` in `/src/templates`

Actual behavior:

- `one-base:static` with `useNunjucks: false` does not create an `index.html` anywhere in the project
- `one-base:static` with `useNunjucks: true` creates a default `index.html` in the root of the project.

### LINKED ISSUE #146: index.html output by one-base:static outputs incorrect file paths
### Steps to reproduce

- Run `yo one-base:static`
- Select `useNunjucks: true`
- Examine the resulting `index.html` in the root of the project

### Expected Output

- Stylesheet `href` is `dist/styles/main.css`
- Script `src` is `dist/scripts/common.bundle.js`

### Actual Output

- Stylesheet `href` is `dist//styles/main.css`
- Script `src` is `dist//scripts/common.bundle.js`

### PR DESCRIPTION
**Pull request by cmalven**
Fixes #145 
Fixes #146 

While I was fixing/testing the above, I noticed that several semi-related aspects of the generator were also broken:

- `globalRoute` import in `main.js` was failing to import due to mix of ES syntaxes
- Inconsistent ES style for importing/exporting modules in `main.js`
- Gulp and Scripts generators would sometimes fail with no deps, so I added default values for those
- Templates were using `templateDist` as the root dir for scripts and styles when they should have been using the `rootDistPath`

Fixes all of the above.

### CODE REVIEW

File: generators/styles/index.js [hunk 1]
```diff
@@ -37,6 +38,8 @@ module.exports = class extends Generator {
 
   writing() {
     this.log(chalk.green('Writing styles files...'));
+    // eslint-disable-next-line
+    console.log('this.props.deps', this.props.deps);
```
Comment (brianjhanson) [inline generators/styles/index.js]: Looks like a log snuck in here.

**Review by brianjhanson — CHANGES_REQUESTED** [review]

File: generators/styles/index.js (hunk 1 above)
Comment (cmalven) [reply generators/styles/index.js]: LOL, that's the issue with those `// eslint-disable` comments!

Comment (cmalven) [reply generators/styles/index.js]: Removed, but of course the tests are going to fail again now. The circle of life.

**Review by brianjhanson — APPROVED** [review]
